export const SOULY_ITEMS = [
  { src: "/souly/0aeptxz9jxrmw0cw7wrbf0std8.webp", title: { ru: "Souly 1", de: "Souly 1" }, desc: { ru: "Персонаж-привидение в разных архетипах.", de: "Geister-Charakter in verschiedenen Archetypen." }, user: { ru: "Mirjana Pavlovic", de: "Mirjana Pavlovic" }, level: 12, achievements: { ru: "Собрала 50 000€ на детские больницы. Организовала 12 благотворительных забегов.", de: "Sammelte 50 000€ für Kinderkliniken. Organisierte 12 Wohltätigkeitsläufe." } },
  { src: "/souly/0befdwccrnrmw0cw7wfrks4jk0.webp", title: { ru: "Souly 2", de: "Souly 2" }, desc: { ru: "Участники получают новые уровни за заслуги.", de: "Teilnehmer erhalten neue Level für Verdienste." }, user: { ru: "Petra Schumann", de: "Petra Schumann" }, level: 8, achievements: { ru: "Помогла 200+ семьям с продуктами. Волонтёр в приютах для бездомных 3 года.", de: "Hilft 200+ Familien mit Lebensmitteln. 3 Jahre Freiwillige in Obdachlosenheimen." } },
  { src: "/souly/0bk5mj9mjdrmy0cw6gavnb6qzw.webp", title: { ru: "Souly 3", de: "Souly 3" }, desc: { ru: "Предстаёт в разных образах сообщества.", de: "Erscheint in verschiedenen Community-Gestalten." }, user: { ru: "Mirjana Pavlovic", de: "Mirjana Pavlovic" }, level: 15, achievements: { ru: "Собрала 50 000€ на детские больницы. Организовала 12 благотворительных забегов.", de: "Sammelte 50 000€ für Kinderkliniken. Organisierte 12 Wohltätigkeitsläufe." } },
  { src: "/souly/0bncbb5g0drmr0cw6ewvp5f3j4.webp", title: { ru: "Souly 4", de: "Souly 4" }, desc: { ru: "Дух Tribe — мистический и тёплый.", de: "Der Geist von Tribe — mystisch und warm." }, user: { ru: "Petra Schumann", de: "Petra Schumann" }, level: 7, achievements: { ru: "Помогла 200+ семьям с продуктами. Волонтёр в приютах для бездомных 3 года.", de: "Hilft 200+ Familien mit Lebensmitteln. 3 Jahre Freiwillige in Obdachlosenheimen." } },
  { src: "/souly/0bqhm1qdyhrmr0cw6g6bd02s90.webp", title: { ru: "Souly 5", de: "Souly 5" }, desc: { ru: "Награды за вклад в сообщество.", de: "Belohnungen für den Beitrag zur Community." }, user: { ru: "Mirjana Pavlovic", de: "Mirjana Pavlovic" }, level: 11, achievements: { ru: "Собрала 50 000€ на детские больницы. Организовала 12 благотворительных забегов.", de: "Sammelte 50 000€ für Kinderkliniken. Organisierte 12 Wohltätigkeitsläufe." } },
  { src: "/souly/0bwcqxygh5rmy0cw7vt963mqpm.webp", title: { ru: "Souly 6", de: "Souly 6" }, desc: { ru: "Элементы природы и технологий.", de: "Elemente aus Natur und Technik." }, user: { ru: "Petra Schumann", de: "Petra Schumann" }, level: 9, achievements: { ru: "Помогла 200+ семьям с продуктами. Волонтёр в приютах для бездомных 3 года.", de: "Hilft 200+ Familien mit Lebensmitteln. 3 Jahre Freiwillige in Obdachlosenheimen." } },
  { src: "/souly/0capwn04xdrmw0cw7y0bxbyteg.webp", title: { ru: "Souly 7", de: "Souly 7" }, desc: { ru: "Единство и благотворительность.", de: "Einheit und Wohltätigkeit." }, user: { ru: "Mirjana Pavlovic", de: "Mirjana Pavlovic" }, level: 14, achievements: { ru: "Собрала 50 000€ на детские больницы. Организовала 12 благотворительных забегов.", de: "Sammelte 50 000€ für Kinderkliniken. Organisierte 12 Wohltätigkeitsläufe." } },
  { src: "/souly/0czk6rqxp9rmt0cw725tprkfq0.webp", title: { ru: "Souly 8", de: "Souly 8" }, desc: { ru: "Креативы о ценностях Tribe.", de: "Kreationen über Tribe-Werte." }, user: { ru: "Petra Schumann", de: "Petra Schumann" }, level: 6, achievements: { ru: "Помогла 200+ семьям с продуктами. Волонтёр в приютах для бездомных 3 года.", de: "Hilft 200+ Familien mit Lebensmitteln. 3 Jahre Freiwillige in Obdachlosenheimen." } },
  { src: "/souly/0d0d9nvac9rmw0cw70eb44yxww.webp", title: { ru: "Souly 9", de: "Souly 9" }, desc: { ru: "Визуализация миссии платформы.", de: "Visualisierung der Plattform-Mission." }, user: { ru: "Mirjana Pavlovic", de: "Mirjana Pavlovic" }, level: 13, achievements: { ru: "Собрала 50 000€ на детские больницы. Организовала 12 благотворительных забегов.", de: "Sammelte 50 000€ für Kinderkliniken. Organisierte 12 Wohltätigkeitsläufe." } },
  { src: "/souly/0d95t6pns9rmt0cw7y3sq4e25g.webp", title: { ru: "Souly 10", de: "Souly 10" }, desc: { ru: "Цифровое искусство и мягкое освещение.", de: "Digitale Kunst und weiches Licht." }, user: { ru: "Petra Schumann", de: "Petra Schumann" }, level: 10, achievements: { ru: "Помогла 200+ семьям с продуктами. Волонтёр в приютах для бездомных 3 года.", de: "Hilft 200+ Familien mit Lebensmitteln. 3 Jahre Freiwillige in Obdachlosenheimen." } },
];
